---
before:
  hooks:
    - go mod tidy
builds:
  - id: traverse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/traverse
    binary: traverse
    ldflags:
      - -s -w -X github.com/joefitzgerald/traverse/main.version={{.Version}} -extldflags '-static'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "traverse_v{{ tolower .Version }}_{{ tolower .Os }}_{{ tolower .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ tolower .Version }}-snapshot-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'
project_name: traverse
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ tolower .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=VERSION={{.Version}}"
      - "--platform=linux/amd64"
brews:
  - name: traverse

    tap:
      owner: joefitzgerald
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/joefitzgerald/traverse"

    # Template of your app's description.
    # Default is empty.
    description: "Build and maintain groups on the basis of reporting hierarchy."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

    install: |-
      bin.install "traverse"
    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/traverse --version"
nfpms:
  - file_name_template: "{{ tolower .ProjectName }}_{{ tolower .Arch }}{{ if .Arm }}v{{ tolower .Arm }}{{ end }}"
    homepage: https://github.com/joefitzgerald/traverse
    description: "Build and maintain groups on the basis of reporting hierarchy."
    maintainer: Joe Fitzgerald <joeyfitz@gmail.com>, Mik Freedman <github@michael-freedman.com
    license: "Apache-2.0"
    vendor: joefitzgerald
    formats:
      - apk
      - deb
      - rpm
